#!/bin/sh

### Package: pbp-install-mesa
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
DEVDIR=$PBPTOOLSDIR/upstream
GITREPO=https://gitlab.freedesktop.org/icecream95
GITTREE=mesa

GITBRANCH=spill-fix
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
meson pbp-build --prefix=~/mesa-test --buildtype=release \
-Dplatforms=wayland,x11 -Ddri-drivers= \
-Dvulkan-drivers= -Dgallium-drivers=panfrost,kmsro,swrast \
-Dlibunwind=false -Dllvm=false

## BUILD
ninja -C pbp-build

ninja -C pbp-build install

## EXIT
exit

## ENJOY
