#!/bin/sh

### Package: pbp-install-libva-v4l2-request
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux, ffmpeg, libva

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
DEVDIR=$PBPTOOLSDIR/upstream
GITREPO=https://github.com/Kwiboo
GITTREE=FFmpeg
GITBRANCH=v4l2-request-hwaccel-4.3.1
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
rm -rf $PKGDIR
git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR

## CONFIGURE

./configure \
        --prefix='/opt' \
        --disable-debug \
        --disable-static \
        --disable-stripping \
        --enable-fontconfig \
        --enable-gmp \
        --enable-gpl \
        --enable-libdrm \
        --enable-libfreetype \
        --enable-libopus \
        --enable-libpulse \
        --enable-libv4l2 \
        --enable-libvpx \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxcb \
        --enable-shared \
        --enable-version3 \
        --enable-libudev \
        --enable-v4l2-request

## BUILD
make -j$(nproc)

## EXIT
exit

## ENJOY
