#!/bin/sh

### Package: pbp-install-libva
### Version: v20200630.2330
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux, ffmpeg

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
DEVDIR=$PBPTOOLSDIR/upstream
GITREPO=https://github.com/maccraft123
GITTREE=libva
GITBRANCH=hantro-h264
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y build-dep libva
  sudo apt-get -y install build-essential coreutils libc-bin wget git patch meson \
  libdrm-dev doxygen pkg-config
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR
## GIT
rm -rf $PKGDIR
git clone $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
meson pbp-build -Dprefix=/opt/ -Dbuildtype=release # --libdir=/usr/local/lib/arm-linux-gnueabihf

## BUILD
ninja -C pbp-build

## EXIT
exit

## ENJOY
