#!/bin/sh

### Package: pbp-install-mesa
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
if [ -z "$CROSS" ]; then
	DEVDIR=$PBPTOOLSDIR/upstream
else
	DEVDIR=$PBPTOOLSDIR/upstream-cross
	[ -f "$PBPTOOLSDIR/$CROSS" ] && export CROSSARGS="--cross-file $PBPTOOLSDIR/$CROSS --libdir=lib/aarch64-linux-gnu" || exit 1
	export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/aarch64-linux-gnu/lib:/usr/aarch64-linux-gnu/lib64"
fi
GITREPO=https://gitlab.freedesktop.org/mesa
GITTREE=mesa

GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## s3tc patch is made by Icecream95, NOT ME
ls s3tc.patch 2>/dev/null || wget https://gitlab.freedesktop.org/snippets/1147/raw -O s3tc.patch
patch -p1 < s3tc.patch

## CLEAN
rm -Rf pbp-build

## CONFIGURE
meson pbp-build --prefix=/opt --buildtype=release \
-Dplatforms=wayland,x11 -Ddri-drivers= \
-Dvulkan-drivers= -Dgallium-drivers=panfrost,kmsro \
-Dlibunwind=false -Dllvm=false $CROSSARGS

## BUILD
ninja -C pbp-build

#sudo ninja -C pbp-build install

## EXIT
exit

## ENJOY
