#!/bin/sh

### Package: pbp-install-mesa
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
if [ -z "$TRIPLET" ]; then
	DEVDIR=$PBPTOOLSDIR/upstream
else
	DEVDIR=$PBPTOOLSDIR/upstream-cross
	[ -f "$PBPTOOLSDIR/$TRIPLET" ] && export CROSSARGS="--cross-file $PBPTOOLSDIR/$TRIPLET --libdir=lib/$TRIPLET" || exit 1
	export QEMU_LD_PREFIX=/usr/$TRIPLET
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/$TRIPLET/lib"
fi
GITREPO=https://gitlab.freedesktop.org/mesa
GITTREE=mesa

GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
meson pbp-build --prefix=/opt --buildtype=release \
-Dplatforms=wayland,x11 -Ddri-drivers= \
-Dvulkan-drivers= -Dgallium-drivers=panfrost,kmsro \
-Dlibunwind=false -Dllvm=false $CROSSARGS

## BUILD
ninja -C pbp-build

#sudo ninja -C pbp-build install

## EXIT
exit

## ENJOY
