#!/bin/bash

PKGROOT=$(pwd)

set -v

cd upstream || cd upstream-cross
cd mesa\_master



grep LIBGL_DRIVERS_PATH $DESTDIR/etc/profile >/dev/null || printf "export LIBGL_DRIVERS_PATH='/opt/lib/$TRIPLET/dri/:/usr/lib/$TRIPLET/dri'" >> $DESTDIR/etc/profile

touch $DESTDIR/etc/ld.so.conf.d/optlibs.conf
echo "/opt/lib/$TRIPLET" > $DESTDIR/etc/ld.so.conf.d/optlibs.conf

ninja -C pbp-build install

rm -rf pbp-build

ldconfig
